#spring.application.name=Stock-Service

spring.datasource.url=jdbc:h2:mem:stockdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sai
spring.datasource.password=sai

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.application.name=stock-service
server.port=8081
alphavantage.api.key=PR637S751G47QTNR
eureka.instance.prefer-ip-address=true