#spring.application.name=Stock-Service
#server.port=8081
#spring.datasource.url=jdbc:h2:mem:stockdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#eureka.client.service-url.default-zone=http://localhost:8761/eureka

server.port=8081
spring.application.name=stock-service
eureka.client.service-url.default-zone=http://localhost:8761/eureka
alpha.vantage.api.key=PR637S751G47QTNR